import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Download, Settings, ChevronLeft, ChevronRight, X, Save, GripVertical } from 'lucide-react';
import { jsPDF } from "jspdf";
import { DndContext, closestCenter, KeyboardSensor, PointerSensor, useSensor, useSensors } from '@dnd-kit/core';
import { arrayMove, SortableContext, sortableKeyboardCoordinates, verticalListSortingStrategy, useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';

const SortableItem = ({ id, chapter, index }) => {
  const { attributes, listeners, setNodeRef, transform, transition } = useSortable({ id });
  
  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
  };
  
  return (
    <div ref={setNodeRef} style={style} className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg border border-gray-200 mb-2">
      <div {...attributes} {...listeners} className="cursor-grab text-gray-400 hover:text-gray-600">
        <GripVertical className="h-5 w-5" />
      </div>
      <div className="flex-1">
        <span className="text-xs font-bold text-gray-500 mr-2">Page {index + 1}</span>
        <span className="text-sm font-medium text-gray-900">{chapter.title}</span>
      </div>
    </div>
  );
};

const EbookViewer = () => {
  const { id } = useParams();
  const [ebook, setEbook] = useState(null);
  const [loading, setLoading] = useState(true);
  const [currentPage, setCurrentPage] = useState(1);
  const [showSettings, setShowSettings] = useState(false);
  const [editTitle, setEditTitle] = useState("");
  const [editChapterTitle, setEditChapterTitle] = useState("");
  const [editChapterText, setEditChapterText] = useState("");
  const [chapters, setChapters] = useState([]);

  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  );

  useEffect(() => {
    let interval;

    const fetchEbook = async () => {
      try {
        const userInfo = JSON.parse(localStorage.getItem('userInfo'));
        const token = userInfo?.token;

        const response = await fetch(`http://localhost:5000/api/ebooks/${id}`, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });
        if (response.ok) {
          const data = await response.json();
          setEbook(data);
          setChapters(data.content || []);
          
          // Stop loading if we have data
          setLoading(false);

          // If still generating, poll again
          if (data.status === 'generating') {
             // The interval will handle the next fetch
          } else {
             // Stop polling if completed or failed
             clearInterval(interval);
          }
        } else {
          setEbook(null);
          setLoading(false);
          clearInterval(interval);
        }
      } catch (error) {
        console.error('Error fetching ebook:', error);
        setEbook(null);
        setLoading(false);
        clearInterval(interval);
      }
    };

    fetchEbook();
    
    // Poll every 3 seconds
    interval = setInterval(fetchEbook, 3000);

    return () => clearInterval(interval);
  }, [id]);

  const handleDownloadPDF = () => {
    if (!ebook) return;

    const doc = new jsPDF();
    
    // Title Page
    doc.setFontSize(24);
    doc.text(ebook.title, 20, 40);
    
    doc.setFontSize(12);
    const descLines = doc.splitTextToSize(ebook.description, 170);
    doc.text(descLines, 20, 60);
    
    doc.setFontSize(10);
    doc.text(`Generated by AI Ebook Creator`, 20, 280);
    
    // Content
    if (ebook.content && ebook.content.length > 0) {
      ebook.content.forEach((chapter) => {
        doc.addPage();
        
        doc.setFontSize(18);
        doc.text(chapter.title, 20, 20);
        
        doc.setFontSize(12);
        const splitText = doc.splitTextToSize(chapter.text, 170);
        doc.text(splitText, 20, 40);
      });
    }

    doc.save(`${ebook.title.replace(/\s+/g, '_')}.pdf`);
  };

  const openSettings = () => {
    setChapters(ebook.content || []);
    const currentContent = ebook.content[currentPage - 1];
    if (currentContent) {
      setEditChapterTitle(currentContent.title);
      setEditChapterText(currentContent.text);
    }
    setShowSettings(true);
  };

  const handleDragEnd = (event) => {
    const { active, over } = event;
    
    if (active.id !== over.id) {
      setChapters((items) => {
        const oldIndex = items.findIndex(item => item._id === active.id || item.title === active.id); // Fallback to title if _id missing
        const newIndex = items.findIndex(item => item._id === over.id || item.title === over.id);
        return arrayMove(items, oldIndex, newIndex);
      });
    }
  };

  const handleUpdateEbook = async (e) => {
    e.preventDefault();
    try {
      const userInfo = JSON.parse(localStorage.getItem('userInfo'));
      const token = userInfo?.token;
      
      // Create a copy of content array from the reordered chapters
      const updatedContent = [...chapters];
      
      // Update the current chapter (if we are editing the current page)
      // Note: If chapters were reordered, 'currentPage' might point to a different chapter now visually,
      // but for simplicity, let's assume user edits the text of the chapter they were viewing *before* opening settings,
      // OR we should disable text editing when reordering. 
      // Better approach: Update the specific chapter in the 'chapters' array that corresponds to the one being edited.
      // However, since we have a list now, let's just save the 'chapters' state which contains the new order.
      // If the user *also* edited the text inputs, we need to apply those changes to the correct chapter in 'chapters'.
      
      // Find the chapter that was originally at 'currentPage - 1'
      // This is tricky if reordering happens. 
      // Let's simplify: The text inputs edit the chapter that was active when modal opened.
      // We need to find that chapter in the 'chapters' array and update it.
      
      const originalChapter = ebook.content[currentPage - 1];
      const chapterIndexInNewOrder = updatedContent.findIndex(c => c._id === originalChapter._id || c.title === originalChapter.title);
      
      if (chapterIndexInNewOrder !== -1) {
         updatedContent[chapterIndexInNewOrder] = {
             ...updatedContent[chapterIndexInNewOrder],
             title: editChapterTitle,
             text: editChapterText
         };
      }

      const response = await fetch(`http://localhost:5000/api/ebooks/${id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          title: editTitle,
          content: updatedContent
        })
      });

      if (response.ok) {
        const updatedEbook = await response.json();
        setEbook(updatedEbook);
        setChapters(updatedEbook.content);
        setShowSettings(false);
      }
    } catch (error) {
      console.error("Error updating ebook", error);
    }
  };

  if (loading) {
    return (
      <div className="flex h-screen items-center justify-center bg-gray-50">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-blue-600 border-t-transparent"></div>
      </div>
    );
  }

  if (!ebook) {
    return (
      <div className="flex h-screen flex-col items-center justify-center bg-gray-50">
        <h2 className="text-xl font-bold text-gray-900">eBook not found</h2>
        <Link to="/dashboard" className="mt-4 text-blue-600 hover:underline">Return to Dashboard</Link>
      </div>
    );
  }

  if (ebook.status === 'generating') {
    return (
      <div className="flex h-screen flex-col items-center justify-center bg-gray-50">
        <div className="h-12 w-12 animate-spin rounded-full border-4 border-indigo-600 border-t-transparent mb-4"></div>
        <h2 className="text-xl font-bold text-gray-900">Generating your eBook...</h2>
        <p className="text-gray-600 mt-2">This may take a few moments. Please refresh the page shortly.</p>
        <Link to="/dashboard" className="mt-6 text-indigo-600 hover:underline">Return to Dashboard</Link>
      </div>
    );
  }

  const currentContent = ebook.content && ebook.content.length > 0 ? ebook.content[currentPage - 1] : null;

  if (!currentContent) {
    return (
      <div className="flex h-screen flex-col items-center justify-center bg-gray-50 p-4 text-center">
        <h2 className="text-xl font-bold text-gray-900">No content available</h2>
        <p className="text-gray-600 mt-2 max-w-md">
          {ebook.status === 'draft' && ebook.description.includes('Generation failed') 
            ? <span className="text-red-500">{ebook.description}</span>
            : "This ebook has no pages yet."}
        </p>
        <Link to="/dashboard" className="mt-4 text-indigo-600 hover:underline">Return to Dashboard</Link>
      </div>
    );
  }

  return (
    <div className="flex h-screen flex-col bg-gray-100">
      {/* Top Bar */}
      <header className="flex h-16 items-center justify-between border-b border-gray-200 bg-white px-4 shadow-sm">
        <div className="flex items-center gap-4">
          <Link to="/dashboard" className="rounded-full p-2 text-gray-500 hover:bg-gray-100 hover:text-gray-900">
            <ArrowLeft className="h-5 w-5" />
          </Link>
          <div>
            <h1 className="text-lg font-semibold text-gray-900">{ebook.title}</h1>
            <p className="text-xs text-gray-500">Page {currentPage} of {ebook.totalPages}</p>
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          <button 
            onClick={handleDownloadPDF}
            className="rounded-full p-2 text-gray-500 hover:bg-gray-100 hover:text-gray-900" 
            title="Download PDF"
          >
            <Download className="h-5 w-5" />
          </button>
          <button 
            onClick={openSettings}
            className="rounded-full p-2 text-gray-500 hover:bg-gray-100 hover:text-gray-900" 
            title="Settings"
          >
            <Settings className="h-5 w-5" />
          </button>
        </div>
      </header>

      {/* Main Content Area */}
      <main className="flex-1 overflow-y-auto p-4 md:p-8">
        <div className="mx-auto max-w-3xl rounded-xl bg-white p-8 shadow-sm md:p-12 min-h-[80vh]">
          <div className="mb-8 border-b border-gray-100 pb-4">
            <h2 className="text-2xl font-bold text-gray-900">{currentContent.title}</h2>
          </div>
          
          <div className="prose prose-lg max-w-none text-gray-700 leading-relaxed whitespace-pre-wrap">
            {currentContent.text}
          </div>
        </div>
      </main>

      {/* Bottom Navigation Bar */}
      <footer className="border-t border-gray-200 bg-white px-4 py-3">
        <div className="mx-auto flex max-w-3xl items-center justify-between">
          <button 
            onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
            disabled={currentPage === 1}
            className="flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 disabled:opacity-50 disabled:hover:bg-transparent"
          >
            <ChevronLeft className="h-4 w-4" />
            Previous
          </button>
          
          <span className="text-sm font-medium text-gray-600">
            {currentPage} / {ebook.totalPages}
          </span>
          
          <button 
            onClick={() => setCurrentPage(p => Math.min(ebook.totalPages, p + 1))}
            disabled={currentPage === ebook.totalPages}
            className="flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 disabled:opacity-50 disabled:hover:bg-transparent"
          >
            Next
            <ChevronRight className="h-4 w-4" />
          </button>
        </div>
      </footer>

      {/* Edit Modal */}
      {showSettings && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
          <div className="w-full max-w-2xl rounded-2xl bg-white p-8 shadow-2xl max-h-[90vh] overflow-y-auto">
            <div className="mb-6 flex items-center justify-between">
              <h2 className="text-2xl font-bold text-gray-900">Edit eBook Content</h2>
              <button 
                onClick={() => setShowSettings(false)}
                className="rounded-full p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-600"
              >
                <X className="h-5 w-5" />
              </button>
            </div>
            
            <form onSubmit={handleUpdateEbook} className="space-y-6">
              <div>
                <label className="mb-2 block text-sm font-medium text-gray-700">eBook Title</label>
                <input
                  type="text"
                  value={editTitle}
                  onChange={(e) => setEditTitle(e.target.value)}
                  className="w-full rounded-xl border border-gray-200 px-4 py-3 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 outline-none"
                />
              </div>

              {/* Chapter Reordering Section */}
              <div>
                <h3 className="mb-3 text-sm font-medium text-gray-700">Organize Chapters</h3>
                <div className="max-h-48 overflow-y-auto rounded-xl border border-gray-200 p-2">
                  <DndContext 
                    sensors={sensors}
                    collisionDetection={closestCenter}
                    onDragEnd={handleDragEnd}
                  >
                    <SortableContext 
                      items={chapters.map(c => c._id || c.title)}
                      strategy={verticalListSortingStrategy}
                    >
                      {chapters.map((chapter, index) => (
                        <SortableItem key={chapter._id || chapter.title} id={chapter._id || chapter.title} chapter={chapter} index={index} />
                      ))}
                    </SortableContext>
                  </DndContext>
                </div>
              </div>
              
              <div className="border-t border-gray-100 pt-6">
                <h3 className="mb-4 text-lg font-semibold text-gray-900">Edit Current Page (Page {currentPage})</h3>
                
                <div className="mb-4">
                  <label className="mb-2 block text-sm font-medium text-gray-700">Chapter Title</label>
                  <input
                    type="text"
                    value={editChapterTitle}
                    onChange={(e) => setEditChapterTitle(e.target.value)}
                    className="w-full rounded-xl border border-gray-200 px-4 py-3 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 outline-none"
                  />
                </div>

                <div>
                  <label className="mb-2 block text-sm font-medium text-gray-700">Content</label>
                  <textarea
                    value={editChapterText}
                    onChange={(e) => setEditChapterText(e.target.value)}
                    className="h-64 w-full rounded-xl border border-gray-200 px-4 py-3 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 outline-none resize-none"
                  />
                </div>
              </div>

              <div className="flex justify-end gap-3 pt-4">
                <button
                  type="button"
                  onClick={() => setShowSettings(false)}
                  className="rounded-xl px-6 py-3 text-sm font-medium text-gray-600 hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="flex items-center gap-2 rounded-xl bg-indigo-600 px-8 py-3 text-sm font-bold text-white shadow-lg hover:bg-indigo-700"
                >
                  <Save className="h-4 w-4" />
                  Save Changes
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default EbookViewer;
